### ISSUE TITLE
Power adapter generates infinite power when converting RF to RF

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Power-Adaptors#4]
Reference: https://github.com/Darkosto/SevTech-Ages/issues/1701

**Comment by darkhax** [comment]
This should have been fixed by https://github.com/Darkhax-Minecraft/Power-Adaptors/commit/dc5ab35e0ef59b7a47e6373c2e62ce736fda8ca0

**Comment by justinrusso** [comment]
IT appears like it has. Thanks!
