### ISSUE TITLE
Adapter continues to accept power even once the buffer is full

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Power-Adaptors#5]
Once the buffer in the adaptor is full, the block appears to still accept energy and continues to drain power from the source.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/1745

#### Versions:
**Power-Adapters:** 1.0.8

**Comment by darkhax** [comment]
Jared said he couldn't reproduce this in the new version, it's possible the other version fixed this as a side effect of the changes.
